### ISSUE TITLE
isa check for "serializer" failed

### ISSUE THREAD

**Issue by TheAthlete** [regru/regru-api-perl#5]
Здравствуйте!
Использую данный модуль с Dancer. При создании домена выдается ошибка:

    isa check for "serializer" failed: JSON::Backend::XS::Supportable=SCALAR(0x3ec1940) is not a JSON instance at (eval 217) line

Изучив ошибку, создал тестовый код:

    use Modern::Perl;
    use utf8;

    use Data::Printer;
    use Regru::API;

    BEGIN { $ENV{PERL_JSON_BACKEND} = 2 } # with JSON::XS
    use JSON -support_by_pp;

    my $client = Regru::API->new(
      username => 'test',
      password => 'test',
    );
    my %contacts = ( 
      contacts => {
        descr       => 'Vschizh site', # Общее описание сделанного заказа. 

        # Данные частного лица
        country     => 'RU', # Двухбуквенный ISO-код страны, гражданином которой является частное лицо.
        person_r    => 'Рюрик Святослав Владимирович', # Фамилия, имя и отчество администратора домена на русском языке в соответствии с паспортными данными. 
        person      => 'Svyatoslav V Ryurik', # Имя, первая буква отчества (без точки) и фамилия администратора домена, записанные латинскими буквами
        passport    => '34 02 651241 выдан 48 о/м г.Москвы 26.12.2003', # Серия и номер паспорта, а также наименование органа, выдавшего паспорт, и дата выдачи (в указанной последовательности, с разделением пробелами). 
        birth_date  => '01.01.1987', # Дата рождения администратора домена в формате ДД.ММ.ГГГГ.

        # Общие поля для .RU/.SU/.РФ доменов 
        p_addr      => '12345, г. Вщиж, ул. Княжеска, д.1, Рюрику Святославу Владимировичу, князю Вщижскому', # Почтовый адрес администратора домена.
        phone       => '+7 495 1234567', # Номер телефона администратора домена.
        e_mail      => 'theathlete@yandex.ru', # Адрес электронной почты администратора домена в формате RFC-822.     
      }
    );

    my $domain = 'theathlete777.ru';

    my $resp = $client->domain->create(
      domain_name => $domain,
      %contacts,
      nss => { 
        ns1 => 'ns1.reg.ru',
        ns2 => 'ns2.reg.ru',
      },
      folder_name => 'theathlete@yandex.ru',
    );

    p $resp;

Данная ошибка выдается в модуле Regru::API::Role::Serializer:

    has serializer => (
        is      => 'rw',
        isa     => sub { croak "$_[0] is not a JSON instance" unless ref $_[0] eq 'JSON' },
        lazy    => 1,
        default => sub { JSON->new->utf8 },
    );

Проблема заключается в том, что Dancer загружает JSON с опцией -support_by_pp в модуле Dancer::Serializer::JSON:

    sub loaded { Dancer::ModuleLoader->load_with_params('JSON', '-support_by_pp') }

Подскажите пожалуйста, как решить данную проблему?

**Comment by Wu-Wu** [comment]
сделал правки, но нет уверенности твёрдой, что сработает. Можно попросить протестировать правильность работы правок? прямо из мастера этого репозитория. клонировать куда-нибудь и добавить путь в модуль/скрипт

```
use lib qw( /path/to/regru-api-perl/lib );
use Regru::API;
...
```

спасибо

**Comment by TheAthlete** [comment]
Проверил, все работает.

**Comment by Wu-Wu** [comment]
Спасибо! За репорт и тестирование! Закрываем )
