### ISSUE TITLE
Frequent failures of t/02-role_serializer.t

### ISSUE THREAD

**Issue by eserte** [regru/regru-api-perl#6]
An overview of CPAN Tester test reports shows quite frequent test failures: http://matrix.cpantesters.org/?dist=Regru-API%200.046
It seems that it's always t/02-role_serializer.t which is failing. My guess is that the error happens if only JSON is installed, but not JSON::XS.

**Comment by akzhan** [comment]
Thanks a lot. @vaneska please respond with
a) Add JSON::XS dependency.
b) Check why pure JSON is not compatible.
c) Move code to JSON::XS competely.

**Comment by Wu-Wu** [comment]
Already resolved in #5
